services:
  flask:
    image: python:3.9
    ports:
      - "5000:5000"
    command: |
      bash -c "pip install flask && python -c '
      from flask import Flask
      app = Flask(__name__)
      @app.route(\"/\")
      def hello(): return \"Hello from Flask!\"
      app.run(host=\"0.0.0.0\", port=5000)
      '"